### ISSUE TITLE
Unable to use <style at="Head"  in  DisplayDriver<Navbar>  

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#14743]
How to use NavbarTop after removal Using <style at="Head"

A while back I asked a question about how to introduce styles in the top menu bar

 https://github.com/OrchardCMS/OrchardCore/issues/13603

At the suggestion of @ns8482e I changed the code to the following

```C#
public class AdminSystemLogViewerShapes : IShapeTableProvider
{
    public void Discover(ShapeTableBuilder builder)
    {
        builder.Describe("Layout")
            .OnCreated(async context =>
            {
                if (context.Shape is IZoneHolding layout)
                {
                    var httpContextAccessor = context.ServiceProvider.GetRequiredService<IHttpContextAccessor>();
                    if (!AdminAttribute.IsApplied(httpContextAccessor.HttpContext))
                    {
                        return;
                    }
                    var auth = context.ServiceProvider.GetRequiredService<IAuthorizationService>();
                    if (!await auth.AuthorizeAsync(httpContextAccessor.HttpContext.User, PermissionsProvider.AccessSystemLog))
                    {
                        return;
                    }
                    await layout.Zones["NavbarTop"].AddAsync(new ShapeViewModel("AdminSystemLogViewer"));
                }
            });
    }
}
```

However, NavbarTop was removed in OC 1.8, I changed it to `DisplayDriver<Navbar>` based on other menu buttons

But the problem came back. Still unable to import styles to Head

```C#
    public class AdminSystemLogViewerShapes : DisplayDriver<Navbar>
    {
        private readonly IAuthorizationService _auth;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public AdminSystemLogViewerShapes(IAuthorizationService auth, IHttpContextAccessor httpContextAccessor)
        {
            _auth = auth;
            _httpContextAccessor = httpContextAccessor;
        }

        public override async Task<IDisplayResult> DisplayAsync(Navbar model, BuildDisplayContext context)
        {
            if (!await _auth.AuthorizeAsync(_httpContextAccessor.HttpContext.User, PermissionsProvider.AccessSystemLog))
            {
                return null;
            }
            return View("AdminSystemLogViewer", model)
                .Location("DetailAdmin", "Content:1");
        }
    

    }
```

**Comment by MikeAlhayek** [comment]
Have you tried adding style to your `AdminSystemLogViewer` view?

```
<style at="Head">
 
</style>
```

**Comment by hyzx86** [comment]
> Have you tried adding style to your `AdminSystemLogViewer` view?
> 
> ```
> <style at="Head">
>  
> </style>
> ```

Will this repeatedly render the elements?

**Comment by hyzx86** [comment]
Hi @MikeAlhayek ，
I want to render a <link> elment  jsut like this:

```razor
    <style asp-name="amis"></style>
    <style asp-name="amis-cxd"></style>
    <style asp-name="amis-helper"></style>
    <style asp-name="amis-iconfont"></style>
```

they can't work in a style block  , I think ~
``` razor
<style at="Head">
    <style asp-name="amis"></style>
    <style asp-name="amis-cxd"></style>
    <style asp-name="amis-helper"></style>
    <style asp-name="amis-iconfont"></style>
</style>

```

**Comment by MikeAlhayek** [comment]
This should work

```
    <style asp-name="amis"></style>
    <style asp-name="amis-cxd"></style>
    <style asp-name="amis-helper"></style>
    <style asp-name="amis-iconfont"></style>
```

However, it does not work because the Navbar shape is created after the head resources is already rendered. PR #14743 should fix this.

But, for now try injecting the resource into `Foot` instead. Foot has not yet been rendered so it should work.

```
    <style at="Foot" asp-name="amis"></style>
    <style at="Foot" asp-name="amis-cxd"></style>
    <style at="Foot" asp-name="amis-helper"></style>
    <style at="Foot" asp-name="amis-iconfont"></style>
```

**Comment by hyzx86** [comment]
Hi @MikeAlhayek ，
Has PR 12312 been released with version [1.8.0-preview-17813](https://cloudsmith.io/~orchardcore/repos/preview/packages/detail/nuget/OrchardCore.Application.Cms.Targets/latest/)?
After I updated the version dependency, it still didn't work

```razor
<style at="Head" asp-name="amis"></style>
<style at="Head" asp-name="amis-cxd"></style>
<style at="Head" asp-name="amis-helper"></style>
<style at="Head" asp-name="amis-iconfont"></style>
```

**Comment by MikeAlhayek** [comment]
@hyzx86 it should be included in 17809+ so you should have seen the fix. Are you use a custom theme or layout?

**Comment by hyzx86** [comment]
> Are you use a custom theme or layout?

Yes ，but my  custom theme is baseon `TheAdmin` and only override the `Layout-Login.cshtml` 

![image](https://github.com/OrchardCMS/OrchardCore/assets/15613121/ee4bc5ef-8c21-4610-a4f9-089a57461531)

**Comment by hyzx86** [comment]
It still not work , even I change theme to `TheAdmin`  
![image](https://github.com/OrchardCMS/OrchardCore/assets/15613121/9abd6203-af8d-4bb5-8fcd-c86c7a8e81d1)

**Comment by MikeAlhayek** [comment]
@hyzx86 strange. It worked when I submitted the PR. I cleaned up my local environment and VS and it returns different environment. maybe some weird caching problem I had. I tested it again using PR #14755 and it seems to be working. If you like, please add a layout file in to your custom theme with the same change as done in  #14755 and see if that fixes the problem.
