### ISSUE TITLE
Fix the location of "Publish" "Save Draft"

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#2255]
In template editing, content editing, etc.
Fix the position of buttons such as "Publish" "Save Draft",
Will it be better?
![1](https://user-images.githubusercontent.com/28694676/44407172-00143c80-a590-11e8-912c-cea4ca60092f.gif)

**Comment by pgy866** [comment]
I also want to put it above, below? But I think she should be on a level alone, not with the user bar interface.

Hidden and hidden near the left side, the mouse moves past, then it shows, how?

**Comment by sebastienros** [comment]
Fixed at the bottom?(but always visible)

We could have a special zone for it in the content editor template, to be able to add button in this "always visible" zone

**Comment by pgy866** [comment]
Fixed at the bottom?(but always visible Or hover automatically at the bottom to hide)

**Comment by agriffard** [comment]
Discussed again in a recent meeting.

Should we display the buttons in a sidebar, find a way to make them always visible?

**Comment by agriffard** [comment]
See also #1907

**Comment by sebastienros** [comment]
I think a sidebar would be ok, as long as it will fall back to the bottom on smaller screens.
There are other things that could use the sidebar (localization).

@matiasmolleja @deanmarcussen @Skrypt who want to do it? It's just a new zone in the Content.Edit.cshtml template to add (the action zone would be inside the same section)

The tabbed UI (Dean's PR) would be on the left of this zone. BTW, @deanmarcussen , how do the tabs behave when resized?

**Comment by deanmarcussen** [comment]
I had a tinker with what @agriffard suggested on #1907

Ended up with this?
![sidebar](https://user-images.githubusercontent.com/13782679/57971512-10bedb00-7987-11e9-9a87-8284f9644cc0.gif)

No tabs in this one, but they'll sit beside it.

Needs to be that far off the top to still show the validation summary and not sit overtop of the title if it extends

**Comment by deanmarcussen** [comment]
Here's another option I played with - same responsive as before, but with a collapse / expand and the title and validation summary moved into a new `Header` zone 

![sidebar-2](https://user-images.githubusercontent.com/13782679/57981089-11a94880-7a2b-11e9-914d-e787e97b04d8.gif)

**Comment by deanmarcussen** [comment]
Third option - not shown - would be to move the collapse / expand to the bottom like the left sidebar and the actions buttons would rise up to sit at the top.

Shame we don't have icons for the action buttons, makes the collapse not so useful.

**Comment by Skrypt** [comment]
![orchard](https://user-images.githubusercontent.com/3228637/57985462-68684f80-7a36-11e9-8f4f-9c24286cade4.gif)

Here is what they do in Ghost CMS. Somehow it seems logic to have the metadata options in a modal sliding tab but they keep the actions buttons in a Bootstrap 4 dropdown menu.

**Comment by deanmarcussen** [comment]
![umbraco](https://user-images.githubusercontent.com/13782679/57999237-98fac880-7acc-11e9-9939-5d3dd8be04cf.gif)

Here's the Umbraco version as well, just to keep collecting ideas!

Personally I don't like the fixed save / publish bar at the bottom. With a fixed bar at bottom and top the viewport just keeps shrinking. In the previous version the Content Cards were Tabs which made navigation simple (but hard to have visibility of the whole content item), in this latest release they've turned them into cards, and included some navigation to the cards via the drop down (probably to appease people that liked having the tabs!)

I agree @Skrypt the sidebar I demo'd looks a bit bare when it just has buttons. 
A good idea to have some metadata shown as well
* Publish / Draft status
* Published / Created / Modified Date
* Clickable url to Content Item 
* Language links
* Link to edit parent if in a list?

**Comment by deanmarcussen** [comment]
Do people think having the sidebar collapsable is useful?

A small `tab` like control fixed to the right side could be the way to show it when collapsed - fitted inside `15p` container padding - and would save the wasted white space visible in option 2

**Comment by deanmarcussen** [comment]
@Skrypt @agriffard @matiasmolleja @hishamco 

Here's a couple of ideas with some metadata as suggested

First with a border

![meta-border](https://user-images.githubusercontent.com/13782679/58231125-1e30e800-7d2e-11e9-96ae-5ae4109b1ae7.gif)

Second with the same background as the left sidebar

![meta-background](https://user-images.githubusercontent.com/13782679/58231152-2ab54080-7d2e-11e9-9167-4393d9bfcf79.gif)

Any opinions?

**Comment by Skrypt** [comment]
To be honest this takes more room in the viewport than a fixed bottom or top bar. I personally prefer the Ghost approach where they simplify it by having a single button that opens-up a  BS4 navigation dropdown that contains a form with options in the top bar. And I would probably keep the idea of the sidebar for other things like editing SEO details. It's not bad but it takes a lot of view space and adds also a lot of white space 😄

**Comment by hishamco** [comment]
Frankly I dislike the sidebar one because it takes much room, perhaps the Umbraco one is very closed to what @sebastienros suggested [above](https://github.com/OrchardCMS/OrchardCore/issues/2255#issuecomment-415547850). I think this doable with bootstrap

I can try this if I have a time ..

**Comment by sebastienros** [comment]
I think WP also uses it. If it's foldable then it wouldn't take too much space. Even though, looking at the editor, there is a lot of whitespace on the right.

**Comment by deanmarcussen** [comment]
@sebastienros Sorry didn't really understand your comment. Can you clarify? 
Do you want a sidebar (collapsable) or a fixed at bottom bar, or an actions dropdown?

Yes width could shrink, Currently around the width of the sidebar, so maybe skinnier. 
To be fair I'm on a mac with a massive viewport. 
Will drop it onto the laptop and see how it looks at 1920. 

@Skrypt Yes to go more Ghost or Umbraco is a bit more of a redesign of the admin layout as a whole really, rather than just tweaking the Content Edit.
I do think editing SEO metadata is more suited to a tab - picking images, and editing metadata feels like big text fields, not little ones. But just opinions :smile:

**Comment by sebastienros** [comment]
Current consensus is to keep all buttons at the bottom, in a sticky zone (for when the canvas is bigger than the page) and for small screens make the buttons a drop down / collapsible (when possible)
