### ISSUE TITLE
Can OrchardCore.Html Module views be Override from Theme?

### ISSUE THREAD

**Issue by stantoxt** [OrchardCMS/OrchardCore#5061]
I can't override Orchardcore.Html Module views.Is it possible for this?

**Comment by jptissot** [comment]
Yes, you can override any views. Just follow the naming convention as described in https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/Templates/

**Comment by stantoxt** [comment]
But it is not working for HtmlBodyPart-Wysiwyg.Edit.cshtml overriding.

**Comment by deanmarcussen** [comment]
probably you are trying to override the admin template in your front end theme. that doesn't work as it's not the active admin theme.

to override the editor templates, i.e. for the admin theme, you either need to 
- `AdminTemplates` feature 
- place template in custom admin theme.

**Comment by stantoxt** [comment]
@deanmarcussen I am a little confused about this,can you give some more explanation.

**Comment by deanmarcussen** [comment]
When you are using the `HtmlBodyPart-Wysiwyg.Edit.cshtml` view it is being consumed by `TheAdmin` theme, as it is an `Edit` template, and `TheAdmin` theme is the theme that consumes it.

If you want to override it you need to do so by one of the techniques above. 

You can't override a view in a theme that is not active at the time of consumption (i.e. using your front end theme won't work, because it is only active on the front end)

Personally when I need to do this, I create a new theme (using Code Gen templates), and set the manifest to have these extra tags
```
    BaseTheme = "TheAdmin",
    Tags = new[] { "admin" }
```

This makes the base theme TheAdmin, and allows the theme to be selected for use as an admin theme.

Because it inherits from `TheAdmin` all the normal admin views are resolved from `TheAdmin` and I can also place extra views in the new theme which can override the originals.

Then in themes in the admin area I select my new theme as active.

**Comment by stantoxt** [comment]
Thanks, @deanmarcussen , let me have a try.

**Comment by marc3lsk** [comment]
I think this is buggy/weird behavior:

- Views/HtmlBodyPart-XXX.Option.cshtml only works in debug mode, i.e. running in IIS Express or IIS mapped to project root. 

- However, it does not work when published (cshtml is set to "Embedded resource"). 

- I am placing the cshtml file inside my main web application, not module or theme.

**Comment by deanmarcussen** [comment]
@marc3lsk can you check the csproj inside your main application.

I think you will need to make sure to have the following to support the views when you are not running in Development mode 
```
<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
```

**Comment by marc3lsk** [comment]
@deanmarcussen I tried AddRazorSupportForMvc and Microsoft.AspNetCore.App reference but still not working. I also hacked csproj so that cshtml was included both as a resource and also compiled into *.Views.dll but still no luck. Here is the screenshot from ILSpy:
![image](https://user-images.githubusercontent.com/12608216/75140581-7ba7fa00-56ef-11ea-8b67-0c1785f35107.png)

**Comment by deanmarcussen** [comment]
Can you post your startup file?

Also what version are you using?

**Comment by marc3lsk** [comment]
https://github.com/marc3lsk/JoditForOrchardCore

Here I created small example. Using latest preview nuget. It works when cshtml is physically present on file system, but not working when published inside dll.

**Comment by deanmarcussen** [comment]
Can you try changing the project line from
`Project Sdk="Microsoft.NET.Sdk.Web">`

to
`Project Sdk="Microsoft.NET.Sdk. Razor">`

**Comment by marc3lsk** [comment]
When I change project from Web to Razor I am no longer able to run IIS Express or publish web site to IIS. My understanding is that it should work either inside module (Razor) or main web application (Web).

**Comment by deanmarcussen** [comment]
Hmm, yes, strange

If I change your `.csproj` to
```
    <EmbeddedResource Include="Views\HtmlBodyPart-Jodit.Edit.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
```

it will copy the views files over as well, and then they are found.

I would generally place these in a module, so I am not sure why they are not showing up when only embedded in the main startup. They do when work moved to a module.

If @jtkech has some time he may be able to advise what we are missing when using from the main startup project.

For info JT I added `<PreserveCompilationContext>true</PreserveCompilationContext>` as well, but without the physical views it was unable to find the shapes.

**Comment by jtkech** [comment]
Yes, it's a limitation for **app level shapes** (not for mvc razor page and views), app level razor shapes need to be there to be harvested as app level liquid shapes.

It works for modules because shapes are also (and always) embedded and then retrieved by our custom embedded file provider. At the app level you would need to set the content root file provider with a composite including the aspnetcore embedded file provider (never tried myself).

So, app level liquid and razor shapes (not mvc pages and views) need to be there, but then you have the choice to use precompiled ones or use runtime compilation, e.g if

    <PreserveCompilationReferences>false</PreserveCompilationReferences>

The `refs` folder is not outputed, you will use the precompiled version, even if the file is there because it is required to be harvested. You can see it by updating the file, the original content is still used meaning there is no runtime compilation. But if you set the above property to true, the `refs` folder is outputed and there is runtime compilation.

If you want to publish all razor files, Set `CopyRazorGenerateFilesToPublishDirectory` property to true as i remember.

Use `Sdk="Microsoft.NET.Sdk.Web">`, then remove

    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>

Also remove the following if you don't want to use the aspnetcore embedded file provide at the app level through the content root file provider (never tried myself).

    <ItemGroup>
      <EmbeddedResource Include="Views\HtmlBodyPart-Jodit.Edit.cshtml" />
      <EmbeddedResource Include="Views\HtmlBodyPart-Jodit.Option.cshtml" />
      <EmbeddedResource Include="Views\_ViewImports.cshtml" />
    </ItemGroup>

Then on building, if you have app level view files, normally it generates a `YourApp.Views.dll`.

**Comment by marc3lsk** [comment]
I ended up with Module solution. I lost couple of hours because of this, maybe it should be mentioned in the docs.
