### ISSUE TITLE
Timeout Expired - Content Item Publish

### ISSUE THREAD

**Issue by RajasekarPR** [OrchardCMS/OrchardCore#6099]
Hi @deanmarcussen @sebastienros 

Getting 500 error page sometimes while publishing the content item. Is it because of yessql lock ?

Error message 

Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
 ---> System.ComponentModel.Win32Exception (258): Unknown error 258
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
ClientConnectionId:a4b1f3f7-483b-48ba-a353-37fd87cd1826
Error Number:-2,State:0,Class:11
ClientConnectionId before routing:de2f694c-d04c-46a1-89d4-fb5e9437f0eb

Kindly do the needful.

**Comment by RajasekarPR** [comment]
@sebastienros @deanmarcussen 

Any update on above issue ?

**Comment by hishamco** [comment]
@RajasekarPR please hold on the team was busy for RC2, but I'm sure someone will reply ASAP, furthermore how you know it's a LOCK issue? because if is that I saw similar issues in the past

**Comment by RajasekarPR** [comment]
@hishamco Since it is timeout issue, it seems we are getting in sqlserver end, so thought it as db lock.

**Comment by hishamco** [comment]
@RajasekarPR  is there steps to reproduce the issue or it happen randomly?

**Comment by jtkech** [comment]
So i searched all issues (opened and closed) that contains `EndExecuteNonQueryInternal`

#5948, #3436, #3096, #2929

**Here we would need a more complete trace** to see from where it happens.

The more related issue seems to be #5948, so maybe a connectivity issue, see the lat comment in #5948.

Meanwhile, **which database** are you using, e.g. sqlite? Are you using **concurrent query**, by using somewhere e.g. `Task.WhenAll()`? E.g. sqlite supports it when done in different scopes, but not in the same scope (using the same session). Are you using workflows? **Which version of OrchardCore?** As some issues have been fixed in the dev branch

**Comment by RajasekarPR** [comment]
@jtkech 

Your PR doesn't fix the issue. Getting same timeout expired issue again.

**Comment by jtkech** [comment]
Okay so i reopen the issue

Can you give us more info, which database, are you using lucene indexing, workflows ... see my comment https://github.com/OrchardCMS/OrchardCore/issues/6099#issuecomment-626298766, we would also need a more complete trace, maybe a connectivity issue, see https://github.com/OrchardCMS/OrchardCore/issues/5948#issuecomment-614107086.

**Comment by deanmarcussen** [comment]
Also helpful to see the connection string you are using - without the password :)

**Comment by RajasekarPR** [comment]
Hi @deanmarcussen @jtkech 

We are not using any lucene indexing or workflows. 

We are using widgetlistpart where we are adding more than 15 widgets(like paragraph, html etc) in it. Initially it is publishing successfully as expected, but after some time, when i am trying to publish it again, throws timeout expired error. 

Database : Sql Server

Connection string :

Data Source=tcp:dummy--beta-sqlserver.database.windows.net,1433;Initial Catalog=dummy--beta-site-db;User Id=dummy--beta-sqlserver-usr@pa-dot-com--beta-sqlserver;Password=dumy;Trusted_Connection=False;Encrypt=True;Connection Timeout=30;Enlist=False;MultipleActiveResultSets=True;ConnectRetryCount=5;ConnectRetryInterval=5

**Comment by deanmarcussen** [comment]
It is hard to tell remotely what you might be experiencing.

There have been some reports of deadlock issues in the underlying `SqlClient` NuGet.

Perhaps you can try upgrading the package yourself and see if it resolves your issue
https://www.nuget.org/packages/Microsoft.Data.SqlClient/
v1.1.3 is the latest release and does contain bug fixes.

Otherwise we would need a further stack trace as @jtkech says.

**Comment by Piedone** [comment]
Closing due to no reply from the author.
