### ISSUE TITLE
µ.CodeAnalysis 3.4.0 issue when building under VStudio

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#6123]
With the last dev after having updated the Lucene version

Afte a quick look seems to be related to a VStudio csharp codeAnalysis issue

Didn't tried to fix it yet as i can build through the donet cmd line

Maybe already fixed as i didn't updated my Visual Studio version for a while

Will try it asap

**Comment by hishamco** [comment]
What kind of issues? I have a little older version too ;)

**Comment by jtkech** [comment]
Just updated Visual Studio

It is now fixed on my side

**Comment by sebastienros** [comment]
What version of VS is required then?

**Comment by jtkech** [comment]
I installed the community version 16.5.4

I was using a version around 16.3.? so not sure what is the minimum version to install.

**Comment by lazcool** [comment]
I still get this error.

I updated to the latest VS, but it also happens when building using dotnet.

**Comment by jtkech** [comment]
I also updated the last public release of dotnet runtime and sdk 3.1.201, i suspect you need some updated `Microsoft.CodeAnalysis.dll` and `Microsoft.CodeAnalysis.CSharp.dll` and so on

**Comment by lazcool** [comment]
I figured out why I was still getting the error - I had `TreatWarningsAsErrors` enabled.

I've removed that, and now I just get a warning.

**Comment by jtkech** [comment]
I didn't remember this property, thanks

But at the end you should not have this warning as we are also using `TreatWarningsAsErrors` in our web application

**Comment by rserj** [comment]
I think it happened after VS update.
As a workaround, you may specify the version of SDK explicitly in the global.json file
https://docs.microsoft.com/en-us/dotnet/core/versions/selection
E.g
```
{
  "sdk": {
    "version": "3.1.402"
  }
}
```
