### ISSUE TITLE
Taxonomy content list filter issues

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#8442]
### Describe the bug
I was testing the taxonomy content list filter and I found some issues with it's logic that meant to all matching content items were returned. This depended on the status of the content item.

### To Reproduce
1. Using the blog theme activate the taxonomy filter feature and set it to work for "tags"
2. Go to Content Definition and list the blog post types.
2. Create a blog post and tag it with one of the tags - I used the "exploration" tag and publish it (Test Post 1)
3. Create a blog post and tag it with the same tag as above eg. "exploration" and save it as draft (Test Post 2)
4. Create a blog post and tag it with the same tag as above eg. "exploration" and publish it, now edit it and save it as draft (Test Post 3)
5. Now use the tags filter to filter on the tag above eg. "exploration" (Show filter defaults to latest) and you will notice that of the 3 posts you created above only the published one (Test Post 1) is in the results - all 3 test posts should have been int he results.
6. Keep the tag filter the same and change the "show" filter to Published... Test Post 1 and Test Post 3 are in the results which is fine.
7. Keep the tag filter the same and change the "show" filter to Unpublished... there are no results but Test Post 2 should have shown.
8. Keep the tag filter the same and change the "show" filter to All Versions... you will notice that of the 3 posts you created above only the published one (Test Post 1) is in the results - all 3 test posts should have been int he results.

### Expected behavior
Here is the expected behavior for the filter combinations and the 3 test posts above:

1. Tag filter "exploration" and Show filter "Latest" - would expect all 3 test posts should show
2. Tag filter "exploration" and Show filter "Owned by me" - all 3 test posts should show
2. Tag filter "exploration" and Show filter "Published" - Test Post 1 and Test Post 3 should show (this filter works).
3. Tag filter "exploration" and Show filter "Unpublished" - Test Post 2 should be show
4. Tag filter "exploration" and Show filter "All versions" - all 3 test posts should show (not sure how All versions differs from latest - doesn't really make sense)

### Screenshots
![taxonomy-filter](https://user-images.githubusercontent.com/2867511/105944857-e146f800-60af-11eb-9171-5774c4f0ef64.gif)

**Comment by scleaver** [comment]
@deanmarcussen - I think this was your creation. I have tried to work out what is wrong with it but it doesn't look like a issue in the taxonomy filter itself as it is straight forward but possibly in how the query works.

**Comment by sebastienros** [comment]
Because the taxonomy index only contains published items, so any filtering will only work with these:
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Taxonomies/Indexing/TaxonomyIndex.cs#L40-L43

**Comment by sebastienros** [comment]
Should be fixed

**Comment by jtkech** [comment]
At least it's already good to not index all the versions including the soft deleted ones. I say that because, working on indexes, i saw some index tables that enlist all versions, maybe normal for the `ContentItemIndex`, but maybe not e.g. for all the sql field indexes (as it was done in O1), e.g. if many items of many types having many fields.

So here, to still not index all versions, we could do the following, and i think i will do a PR to suggest the same on some other index tables.

                    if (!contentItem.IsPublished() && !contentItem.Latest)
                    {
                        return null;
                    }

**Comment by scleaver** [comment]
I agree @jtkech
