### ISSUE TITLE
Datepicker is shown transparent

### ISSUE THREAD

**Issue by LMSSonos** [OrchardCMS/OrchardCore#9771]
### Describe the bug

The datepicker does not show correctly in nightly version 1.0.0-rc2-16322 (was working in 1.0.0-rc2-13450). See  the screenshot

### Screenshots
![datepicker-transparent](https://user-images.githubusercontent.com/19758451/123448318-14e46a80-d5db-11eb-8d50-26f574446b13.gif)

**Comment by deanmarcussen** [comment]
Funny was just about to open an issue / regression from here https://github.com/OrchardCMS/OrchardCore/pull/9699/files

@Skrypt I think you renamed the admin script from `admin` to `the-admin`

But we have so many scripts that have a `depends-on="admin"` to load `jQuery` and sometimes `bootstrap`, so there is a bunch of stuff broken at the moment.

Fixed on yesterday here https://github.com/OrchardCMS/OrchardCore/pull/9766 but not sure it was the correct fix - was just seeing things not working on the Audit Trail branch.

**Comment by deanmarcussen** [comment]
The issue is mostly related to the ordering of scripts, where they are now being ordered later than they should be. not sure about the boostrap.js - can't remember if this is supposed to be part of the admin.js, or loaded seperately.

**Comment by LMSSonos** [comment]
@agriffard are you sure this issue is solved. I tested 1.0.0-rc2-16317 and still have the transparent calender

**Comment by agriffard** [comment]
Latest version is `1.0.0-rc2-16327`

**Comment by LMSSonos** [comment]
Thanks, Tested with `1.0.0-rc2-16328` and latest Firefox and Chrome, issue still persists on my PC. Also tried to delete the browser cache and switched between dark and bright mode.
